version: '3.8'

services:
  webrtc-app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - TURN_SERVER_URL=turn:your-turn-server.com:3478
      - TURN_USERNAME=your-username
      - TURN_CREDENTIAL=your-credential
    restart: unless-stopped
    networks:
      - webrtc-network

  coturn:
    image: coturn/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    networks:
      - webrtc-network

networks:
  webrtc-network:
    driver: bridge